src/Entity/Thread.php
<?php

namespace App\Entity;

use App\Entity\Category;
use App\Repository\ThreadRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ThreadRepository::class)]
class Thread
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 6)]
    private ?string $status = null;

    #[ORM\Column(length: 50)]
    private ?string $title = null;

    #[ORM\Column(length: 100)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $main = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $edited = null;

    /**
     * @var Collection<int, ThreadVote>
     */
    #[ORM\OneToMany(targetEntity: ThreadVote::class, mappedBy: 'thread', orphanRemoval: true)]
    private Collection $threadVotes;

    /**
     * @var Collection<int, Response>
     */
    #[ORM\OneToMany(targetEntity: Response::class, mappedBy: 'thread')]
    private Collection $responses;

    #[ORM\ManyToOne(inversedBy: 'thread')]
    private ?User $user = null;

    /**
     * @var Collection<int, Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'threads')]
    private Collection $category;

    public function __construct()
    {
        $this->responses = new ArrayCollection();
        $this->threadVotes = new ArrayCollection();
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getMain(): ?string
    {
        return $this->main;
    }

    public function setMain(string $main): static
    {
        $this->main = $main;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): static
    {
        $this->created = $created;

        return $this;
    }

    public function getEdited(): ?\DateTimeInterface
    {
        return $this->edited;
    }

    public function setEdited(\DateTimeInterface $edited): static
    {
        $this->edited = $edited;

        return $this;
    }

    /**
     * @return Collection<int, ThreadVote>
     */
    public function getThreadVotes(): Collection
    {
        return $this->threadVotes;
    }

    public function getTotalVotes(): int
    {
        $count = 0;
        foreach ($this->getThreadVotes() as $vote) {
            if ($vote->isVote()) {
                $count++;
            }

            if (!$vote->isVote()) {
                $count--;
            }
        }
        return $count;
    }

    public function addThreadVote(ThreadVote $threadVote): static
    {
        if (!$this->threadVotes->contains($threadVote)) {
            $this->threadVotes->add($threadVote);
            $threadVote->setThread($this);
        }

        return $this;
    }

    public function removeThreadVote(ThreadVote $threadVote): static
    {
        if ($this->threadVotes->removeElement($threadVote)) {
            // set the owning side to null (unless already changed)
            if ($threadVote->getThread() === $this) {
                $threadVote->setThread(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Response>
     */
    public function getResponses(): Collection
    {
        return $this->responses;
    }

    public function addResponse(Response $response): static
    {
        if (!$this->responses->contains($response)) {
            $this->responses->add($response);
            $response->setThread($this);
        }

        return $this;
    }

    public function removeResponse(Response $response): static
    {
        if ($this->responses->removeElement($response)) {
            // set the owning side to null (unless already changed)
            if ($response->getThread() === $this) {
                $response->setThread(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(category $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(category $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }
}

src/Controller/ThreadController.php
<?php

namespace App\Controller;

use App\Entity\Response as ResponseEntity;
use App\Entity\ResponseVote;
use App\Entity\Thread;
use App\Entity\ThreadVote;
use App\Form\ResponseCreationType;
use App\Form\ThreadCreationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ThreadController extends AbstractController
{
    #[Route('/', name: 'app_thread_list')]
    public function threadList(EntityManagerInterface $entityManager): Response
    {
        $threadRepository = $entityManager->getRepository(Thread::class);

        $threads = $threadRepository->findAll();

        return $this->render('thread/threadList.html.twig', [
            'threads' => $threads
        ]);
    }

    #[Route('/thread/creation', name: 'app_thread_creation')]
    public function createThread(Request $request, EntityManagerInterface $entityManager): Response
    {
        $thread = new Thread();
        $thread->setStatus('open');
        $thread->setCreated(new \DateTimeImmutable());
        $thread->setEdited(new \DateTimeImmutable());
        $thread->setUser($this->getUser());

        $form = $this->createForm(ThreadCreationType::class, $thread);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($thread);
            $entityManager->flush();

            return $this->redirectToRoute('app_thread_list', ['id' => $thread->getId()]);
        }

        return $this->render('thread/threadCreation.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/thread/{id}', name: 'app_thread')]
    public function threadDetails($id, EntityManagerInterface $entityManager): Response
    {

        $threadRepository = $entityManager->getRepository(Thread::class);

        $threads = $threadRepository->find($id);
        $responses = $threads->getResponses();

        return $this->render('thread/threadDetails.html.twig', [
            'threads' => $threads,
            'responses' => $responses
        ]);
    }

    #[Route('/thread/{id}/voteUp', name: 'app_thread_vote_up')]
    public function voteUp(Thread $thread, Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return new Response('Invalid request', 400);
        }

        $existingVote = $entityManager->getRepository(ThreadVote::class)->findOneBy([
            'thread' => $thread,
            'user' => $user
        ]);

        if ($existingVote) {
            if (!$existingVote->isVote()) {
                $existingVote->setVote(true);
                $entityManager->flush();
            } else {
                $entityManager->remove($existingVote);
                $entityManager->flush();
            }

            return $this->redirectToRoute('app_thread', ['id' => $thread->getId()]);
        }

        $threadVote = new ThreadVote();
        $threadVote->setThread($thread);
        $threadVote->setUser($user);
        $threadVote->setVote(true);

        $entityManager->persist($threadVote);
        $entityManager->flush();

        return $this->redirectToRoute('app_thread', ['id' => $thread->getId()]);
    }

    #[Route('/thread/{id}/voteDown', name: 'app_thread_vote_down')]
    public function voteDown(Thread $thread, Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return new Response('Invalid request', 400);
        }

        $existingVote = $entityManager->getRepository(ThreadVote::class)->findOneBy([
            'thread' => $thread,
            'user' => $user
        ]);

        if ($existingVote) {
            if ($existingVote->isVote()) {
                $existingVote->setVote(false);
                $entityManager->flush();
            } else {
                $entityManager->remove($existingVote);
                $entityManager->flush();
            }

            return $this->redirectToRoute('app_thread', ['id' => $thread->getId()]);
        }

        $threadVote = new ThreadVote();
        $threadVote->setThread($thread);
        $threadVote->setUser($user);
        $threadVote->setVote(false);

        $entityManager->persist($threadVote);
        $entityManager->flush();

        return $this->redirectToRoute('app_thread', ['id' => $thread->getId()]);
    }

    #[Route('/response/{id}/voteUp', name: 'app_response_vote_up')]
    public function voteResponseUp(ResponseEntity $response, Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
    
        if (!$user) {
            return new Response('Invalid request', 400);
        }
    
        $existingVote = $entityManager->getRepository(ResponseVote::class)->findOneBy([
            'response' => $response,
            'user' => $user
        ]);
    
        if ($existingVote) {
            if (!$existingVote->isVote()) {
                $existingVote->setVote(true);
                $entityManager->flush();
            } else {
                $entityManager->remove($existingVote);
                $entityManager->flush();
            }
    
            return $this->redirectToRoute('app_thread', ['id' => $response->getThread()->getId()]);
        }
    
        $responseVote = new ResponseVote();
        $responseVote->setResponse($response);
        $responseVote->setUser($user);
        $responseVote->setVote(true);
    
        $entityManager->persist($responseVote);
        $entityManager->flush();
    
        return $this->redirectToRoute('app_thread', ['id' => $response->getThread()->getId()]);
    }
    

    #[Route('/response/{id}/voteDown', name: 'app_response_vote_down')]
    public function voteResponseDown(ResponseEntity $response, Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
    
        if (!$user) {
            return new Response('Invalid request', 400);
        }
    
        $existingVote = $entityManager->getRepository(ResponseVote::class)->findOneBy([
            'response' => $response,
            'user' => $user
        ]);
    
        if ($existingVote) {
            if ($existingVote->isVote()) {
                $existingVote->setVote(false);
                $entityManager->flush();
            } else {
                $entityManager->remove($existingVote);
                $entityManager->flush();
            }
    
            return $this->redirectToRoute('app_thread', ['id' => $response->getThread()->getId()]);
        }
    
        $responseVote = new ResponseVote();
        $responseVote->setResponse($response);
        $responseVote->setUser($user);
        $responseVote->setVote(false);
    
        $entityManager->persist($responseVote);
        $entityManager->flush();
    
        return $this->redirectToRoute('app_thread', ['id' => $response->getThread()->getId()]);
    }

    #[Route('/thread/{id}/edit', name: 'app_thread_edit')]
    public function editThread(Request $request, Thread $thread, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ThreadCreationType::class, $thread);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_thread_list', ['id' => $thread->getId()]);
        }

        return $this->render('thread/threadEdit.html.twig', [
            'form' => $form->createView(),
            'thread' => $thread,
        ]);
    }

    #[Route('/thread/{id}/response/create', name: 'app_response_create')]
    public function createResponse(Request $request, Thread $thread, EntityManagerInterface $entityManager): Response
    {
        $response = new ResponseEntity();
        $response->setThread($thread);
        $response->setUser($this->getUser());
        $response->setCreated(new \DateTimeImmutable());
        $response->setEdited(new \DateTimeImmutable());

        $form = $this->createForm(ResponseCreationType::class, $response);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($response);
            $entityManager->flush();

            return $this->redirectToRoute('app_thread', ['id' => $thread->getId()]);
        }

        return $this->render('thread/threadResponseCreation.html.twig', [
            'form' => $form->createView(),
            'thread' => $thread,
        ]);
    }

    #[Route('/responses/{id}', name: 'app_response_delete', methods: ['DELETE', 'POST'])]
    public function delete(ResponseEntity $response, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        if ($user === null || (!in_array('ROLE_ADMIN', $user->getRoles()) && $response->getUser() !== $user && $response->getThread()->getUser() !== $user)) {
            throw new AccessDeniedException('You do not have permission to delete this response.');
        }

        $entityManager->remove($response);
        $entityManager->flush();

        return $this->redirectToRoute('app_thread', ['id' => $response->getThread()->getId()]);
    }
}

templates/thread/threadCreation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Thread
{% endblock %}

{% block body %}
	<div class="threadCreationBox">
		<h1>Create Thread</h1>

		{{ form_start(form, {'attr': {'class': 'column'}}) }}
		<div class="creationFormItem">
			{{ form_label(form.title, 'Title', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="creationFormItem">
			{{ form_label(form.category, 'Category', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.category, {'attr': {'class': 'form-select'}}) }}
		</div>
		<div class="creationFormItem">
			{{ form_label(form.description, 'Description', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
		</div>
        <div class="creationFormItem">
			{{ form_label(form.main, 'Main', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.main, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="creationFormItem createButtonBox">
			<button type="submit" class="btn createbutton">Create</button>
		</div>
		{{ form_end(form) }}
	</div>

{% endblock %}

templates/thread/threadDetails.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello threadsController!
{% endblock %}

{% block body %}


	<div class="d-flex justify-content-center align-items-center threadMainContainer" style="height: 100vh;">
		<div class="card" style="width: 600px;">
			<div class="card-body">
				<div class="d-flex justify-content-between align-items-center mb-3">
					{% if threads.status == 'open' %}
						<span class="badge bg-success">Open</span>
					{% else %}
						<span class="badge bg-danger">Closed</span>
					{% endif %}
					<small class="text-muted">Edited:
						{{ threads.edited|date('d-m-Y H:i') }}</small>
					{% if threads.user == app.user %}
						<a href="{{ path('app_thread_edit', {'id': threads.id}) }}" class="btn btn-sm btn-primary ms-2">Edit</a>
					{% endif %}
					{% if is_granted('ROLE_ADMIN') %}
						<form action="{{ path('app_thread_delete', {'id': threads.id}) }}" method="post" style="display: inline-block;">
							<input type="hidden" name="_method" value="DELETE">
							<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ threads.id) }}">
							<button type="submit" class="btn btn-sm btn-danger ms-2" onclick="return confirm('Are you sure you want to delete this thread?')">Delete</button>
						</form>
					{% endif %}
				</div>
				<h1 class="card-title cardText">{{ threads.title }}</h1>
				<p class="card-text cardText">{{ threads.description }}</p>
				<p class="card-text cardText">{{ threads.main }}</p>
				<small class="text-muted">Created:
					{{ threads.created|date('d-m-Y H:i') }}</small>
				<div class="d-flex justify-content-between align-items-center mt-3">
					<div class="d-flex align-items-center">
						<form action="{{ path('app_thread_vote_up', {'id': threads.id, 'direction': 'up'}) }}" method="post" style="display: inline-block;">
							<input type="hidden" name="_token" value="{{ csrf_token('vote' ~ threads.id ~ 'up') }}">
							<button type="submit" class="btn btn-sm btn-primary me-2">Vote Up</button>
						</form>
						<span class="badge bg-secondary">{{ threads.totalVotes }}</span>
						<form action="{{ path('app_thread_vote_down', {'id': threads.id, 'direction': 'down'}) }}" method="post" style="display: inline-block;">
							<input type="hidden" name="_token" value="{{ csrf_token('vote' ~ threads.id ~ 'down') }}">
							<button type="submit" class="btn btn-sm btn-primary ms-2">Vote Down</button>
						</form>
					</div>
					<a href="{{ path('app_response_create', {'id': threads.id}) }}" class="btn btn-sm btn-primary">Create Response</a>
				</div>
				<div class="mt-3">
					{% for response in responses %}
						<div class="card mb-2">
							<div class="card-body">
								<small class="text-muted">Posted :
									{{ response.created|date('d-m-Y H:i') }}</small>
								<div class="d-flex justify-content-between align-items-center mb-2">
									<big>
										{{ response.user.username }}
										<br>
									</big>


									<div>
										{% if is_granted('ROLE_ADMIN') or response.user == app.user %}
											<form method="POST" action="{{ path('app_response_delete', {'id': response.id}) }}">
												<input type="hidden" name="_method" value="DELETE">
												<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ response.id) }}">
												<button type="submit" class="btn btn-sm btn-danger">Delete</button>
											</form>
										{% endif %}
									</div>
								</div>
								<p class="card-text responseMainText">{{ response.main }}</p>
								<a href="{{ path('app_response_vote_up', {'id': response.id}) }}" class="btn btn-sm btn-primary me-2">
									Vote Up
								</a>
								<span class="badge bg-secondary">{{ response.totalVotes }}</span>
								<a href="{{ path('app_response_vote_down', {'id': response.id}) }}" class="btn btn-sm btn-primary me-2">
									Vote Down
								</a>
							</div>
						</div>
					{% endfor %}


				</div>
			</div>
		</div>
	</div>


{% endblock %}

templates/thread/threadEdit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Thread
{% endblock %}

{% block body %}
	<div class="threadCreationBox">
		<h1>Edit Thread</h1>

		{{ form_start(form, {'attr': {'class': 'column'}}) }}
		<div class="creationFormItem">
			{{ form_label(form.title, 'Title', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.title, {'attr': {'class': 'form-control', 'value': thread.title}}) }}
		</div>
		<div class="creationFormItem">
			{{ form_label(form.category, 'Category', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.category, {'attr': {'class': 'form-select'}}) }}
		</div>
		<div class="creationFormItem">
			{{ form_label(form.description, 'Description', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.description, {'attr': {'class': 'form-control', 'value': thread.description}}) }}
		</div>
        <div class="creationFormItem">
			{{ form_label(form.main, 'Main', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.main, {'attr': {'class': 'form-control', 'value': thread.main}}) }}
		</div>
		<div class="creationFormItem createButtonBox">
			<button type="submit" class="btn createbutton">Save Changes</button>
		</div>
		{{ form_end(form) }}
	</div>

{% endblock %}

templates/thread/threadList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ThreadController!
{% endblock %}

{% block body %}
    <div class="d-flex flex-column align-items-center threadContainer" style="height: 100vh;">
        {% for thread in threads %}
            <div class="mb-3">
                <a href="{{ path('app_thread', {'id': thread.id}) }}">
                    <div class="d-flex justify-content-center align-items-center" style="width: fit-content; height: fit-content;">
                        <div class="card" style="width: 500px; height: 250px;">
                            <div class="card-body d-flex flex-column justify-content-between">
                                <div class="d-flex justify-content-between align-items-center">
                                    {% if thread.status == 'open' %}
                                        <span class="badge bg-success">Open</span>
                                    {% else %}
                                        <span class="badge bg-danger">Closed</span>
                                    {% endif %}
                                    <small class="text-muted">Edited:
                                        {{ thread.edited|date('d-m-Y H:i') }}</small>
                                </div>
                                <h1 class="card-title threadTitle">{{ thread.title }}</h1>
                                <p class="card-text cardText">{{ thread.main }}</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/thread/threadResponseCreation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Response
{% endblock %}

{% block body %}
	<div class="threadCreationBox">
		<h1>Create Response</h1>

		{{ form_start(form, {'attr': {'class': 'column'}}) }}
		<div class="creationFormItem">
			{{ form_label(form.main, 'Main', {'label_attr': {'class': 'form-label'}}) }}
			{{ form_widget(form.main, {'attr': {'class': 'form-control'}}) }}
		</div>
		<div class="creationFormItem createButtonBox">
			<button type="submit" class="btn createbutton">Create Response</button>
		</div>
		{{ form_end(form) }}
	</div>

{% endblock %}